// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  main_ai: dynamic(() => import("./MainAi")),
  rich_text: dynamic(() => import("./RichText")),
};
